spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kitty
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      max-wait: 10000
  jpa:
    show-sql: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.ssm.shop.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  tomcat:
    uri-encoding: utf-8
#自定义常量图片上传路径
user-param:
  uploadPath: D:\\images\\